imports:
    - { resource: environment.yml }
    - { resource: parameters.yml }
    - { resource: ../../data/environment.yml }
    - { resource: ../../data/parameters.yml }
    - { resource: @NetgustoBootCampBundle/ParameterProcessor/Environment.php }
    - { resource: @NetgustoBootCampBundle/ParameterProcessor/Database.php }
    
    # Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

services: